### ISSUE TITLE
Airflow Pools 

### ISSUE THREAD

**Issue by mskazy** [bitnami/bitnami-docker-airflow-scheduler#12]
### Name and Version

2.2.3 and master

### What steps will reproduce the bug?

1. Set the AIRFLOW_POOL_NAME, AIRFLOW_POOL_SIZE, AIRFLOW_POOL_DESC in environment
2. Try to boot up the compose environment
3. Airflow container will not boot up, log indicates it tries to create the pool and crashes

### What is the expected behavior?

A new pool is created when booting up airflow

### What do you see instead?

Airflow does not boot at all.  The log reaches the "Creating Airflow Pool" and then crashes

### Additional information

https://github.com/bitnami/bitnami-docker-airflow-scheduler/blob/master/2/debian-10/rootfs/opt/bitnami/scripts/libairflow.sh#L408

This `airflow pool` command used to create the pool was deprecated in the Airflow version installed in the image.  This can be seen when booting up the image and trying to run the `airflow pool` command manually.  The new syntax should use `airflow pools set`

https://airflow.apache.org/docs/apache-airflow/stable/cli-and-env-variables-ref.html#pools

```
airflow pool -s new_pool 1 description
airflow command error: argument GROUP_OR_COMMAND: `airflow pool` command, has been removed, please use `airflow pools`, see help above.
```

**Comment by javsalgar** [comment]
Hi,

Indeed, it seems that the command we are using is deprecated. Would you like to submit a PR updating it with the correct value?
