### ISSUE TITLE
Help with auto deleting scheduler logs

### ISSUE THREAD

**Issue by aerasoft** [bitnami/bitnami-docker-airflow-scheduler#3]
The scheduler logs stored here  /var/lib/docker/devicemapper/mnt/e92098795fb366bc2fb1e549158f1fdcbe3b51132262b317e2a868d333e303d9/rootfs/opt/bitnami/airflow/logs/scheduler/ has increased in size and right now l am running out of Disk space. Also, the log files are now read only causing my scheduler not to work. How do l fix this issue? How do l periodically clear these logs?

**Comment by aerasoft** [comment]
I get these errors when l try to remove the files 

rm: cannot remove ‘/var/lib/docker/devicemapper/mnt/e92098795fb366bc2fb1e549158f1fdcbe3b51132262b317e2a868d333e303d9/rootfs/opt/bitnami/airflow/logs/scheduler/2019-09-25/store_metric.py.log’: Read-only file system
rm: cannot remove ‘/var/lib/docker/devicemapper/mnt/e92098795fb366bc2fb1e549158f1fdcbe3b51132262b317e2a868d333e303d9/rootfs/opt/bitnami/airflow/logs/scheduler/2019-09-25/xxx.py.log’: Read-only file system
rm: cannot remove ‘/var/lib/docker/devicemapper/mnt/e92098795fb366bc2fb1e549158f1fdcbe3b51132262b317e2a868d333e303d9/rootfs/opt/bitnami/airflow/logs/scheduler/2019-09-25/xxx.py.log’: Read-only file system
rm: cannot remove ‘/var/lib/docker/devicemapper/mnt/e92098795fb366bc2fb1e549158f1fdcbe3b51132262b317e2a868d333e303d9/rootfs/opt/bitnami/airflow/logs/scheduler/2019-09-25/xxxx.py.log’: Read-only file system

**Comment by andresbono** [comment]
Hi @aerasoft, can you access to the container and empty the log files there?

```
docker exec -it YOUR_SCHEDULER_CONTAINER bash
```

Then, you should be able to clean the contents of the files by echoing an empty line and doing a redirection:

```
echo >/opt/bitnami/airflow/logs/scheduler/THE_FILE_THAT_YOU_WANT_TO_ERASE
```

---

Are the logs being added to different folders each day?
