### ISSUE TITLE
Python package installation in image

### ISSUE THREAD

**Issue by emerson131** [bitnami/bitnami-docker-airflow-scheduler#5]
Hi.

Im looking to add extra python packages via pip onto the airflow containers. Going by the architecture im assuming that in order for my tasks to run, i will need to add these packages on the airflow worker container. In the docker file for the airflow-webserver container i can see a run.sh file that looks for the requirements file in order to install these dependencies. However i can see no such entry for the worker and hence i cant see a mechanism that lets me add these packages when i start up the container.

Woudl appreciate some guidance on how i can get this done since i would ideally want the packages installed when my container first starts up instead of installing it via exec

Thanks
Emerson

**Comment by joancafom** [comment]
Hi @emerson131 and @wslulciuc,

Thanks for using bitnami containers 😁. I will handle the changes and link back to this issue once they are done. Just for other users to know, there is a workaround regarding this (see [ref](https://github.com/bitnami/bitnami-docker-airflow-worker/issues/5#issuecomment-670723397)), although I agree that providing with the ability of installing new python packages built-in comes handy.

Thanks!

**Comment by wslulciuc** [comment]
Great, thanks @joancafom!

**Comment by joancafom** [comment]
Hi again,

My pleasure! Happy to inform you that the latest release https://github.com/bitnami/bitnami-docker-airflow-scheduler/commit/64b240903604924bb2c3fe19db4ac99bc13c3cb1 already implements the changes 🎉

Thanks for your issue!

**Comment by wslulciuc** [comment]
@joancafom Awesome! Just pulled down the new image, works great!

**Comment by rafariossaa** [comment]
Hi,
  You are welcome.
  I am closing this issue now. I find any problem leave a comment or open a new issue.
