### ISSUE TITLE
No module named 'airflow.providers.snowflake'

### ISSUE THREAD

**Issue by sobee07** [bitnami/bitnami-docker-airflow-scheduler#7]
**Description**

I am trying to add snowflake connector in airflow but in spite of adding the python modules , the snowflake connector does not show up in the airflow UI

**Steps to reproduce the issue:**

1. Used below docker compose file 

version: '2'

services:
  postgresql:
    image: docker.io/bitnami/postgresql:10
    volumes:
      - 'postgresql_data:/bitnami/postgresql'
      - ./dags:/opt/bitnami/airflow/dags
      - ./plugins:/opt/bitnami/airflow/plugins
      - ~/.aws:/root/.aws
    environment:
      - POSTGRESQL_DATABASE=bitnami_airflow
      - POSTGRESQL_USERNAME=bn_airflow
      - POSTGRESQL_PASSWORD=bitnami1
      - ALLOW_EMPTY_PASSWORD=yes
      - AIRFLOW_FERNET_KEY=zm2MeC7oI8Xk9esl5BFaaXz34t-iAhdgasjdjsdh=
  redis:
    image: docker.io/bitnami/redis:6.0
    volumes:
      - 'redis_data:/bitnami'
      - ./dags:/opt/bitnami/airflow/dags
      - ./plugins:/opt/bitnami/airflow/plugins
      - ~/.aws:/root/.aws
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - AIRFLOW_FERNET_KEY=zm2MeC7oI8Xk9esl5BFaaXz34t-iAhdgasjdjsdh=
  airflow-scheduler:
    # TODO: to be reverted to use proper registry/distro on T39132
    # image: docker.io/bitnami/airflow-scheduler:2
    image: docker.io/bitnami/airflow-scheduler:2
    environment:
      - AIRFLOW_DATABASE_NAME=bitnami_airflow
      - AIRFLOW_DATABASE_USERNAME=bn_airflow
      - AIRFLOW_DATABASE_PASSWORD=bitnami1
      - AIRFLOW_EXECUTOR=CeleryExecutor
      - AIRFLOW_WEBSERVER_HOST=airflow
      - AIRFLOW_FERNET_KEY=zm2MeC7oI8Xk9esl5BFaaXz34t-iAhdgasjdjsdh=
      - AWS_CONFIG_FILE=/root/.aws/config
      - AIRFLOW_LOAD_EXAMPLES=no
    volumes:
      - airflow_scheduler_data:/bitnami
      - ./dags:/opt/bitnami/airflow/dags
      - ./plugins:/opt/bitnami/airflow/plugins
      - ~/.aws:/root/.aws
  airflow-worker:
    # TODO: to be reverted to use proper registry/distro on T39132
    # image: docker.io/bitnami/airflow-worker:2
    image: docker.io/bitnami/airflow-worker:2
    environment:
      - AIRFLOW_DATABASE_NAME=bitnami_airflow
      - AIRFLOW_DATABASE_USERNAME=bn_airflow
      - AIRFLOW_DATABASE_PASSWORD=bitnami1
      - AIRFLOW_EXECUTOR=CeleryExecutor
      - AIRFLOW_WEBSERVER_HOST=airflow
      - AIRFLOW_FERNET_KEY=zm2MeC7oI8Xk9esl5BFaaXz34t-iAhdgasjdjsdh=
      - AWS_CONFIG_FILE=/root/.aws/config
      - AIRFLOW_LOAD_EXAMPLES=no
    volumes:
      - airflow_worker_data:/bitnami
      - ./dags:/opt/bitnami/airflow/dags
      - ./plugins:/opt/bitnami/airflow/plugins
      - ~/.aws:/root/.aws
  airflow:
    image: docker.io/bitnami/airflow:2
    environment:
      - AIRFLOW_DATABASE_NAME=bitnami_airflow
      - AIRFLOW_DATABASE_USERNAME=bn_airflow
      - AIRFLOW_DATABASE_PASSWORD=bitnami1
      - AIRFLOW_EXECUTOR=CeleryExecutor
      - AIRFLOW_FERNET_KEY=zm2MeC7oI8Xk9esl5BFaaXz34t-iAhdgasjdjsdh=
      - AWS_CONFIG_FILE=/root/.aws/config
      - AIRFLOW_LOAD_EXAMPLES=no
    ports:
      - '8080:8080'
    volumes:
      - airflow_data:/bitnami
      - ./dags:/opt/bitnami/airflow/dags
      - ./plugins:/opt/bitnami/airflow/plugins
      - ~/.aws:/root/.aws
volumes:
  airflow_scheduler_data:
    driver: local
  airflow_worker_data:
    driver: local
  airflow_data:
    driver: local
  postgresql_data:
    driver: local
  redis_data:
    driver: local

2. Made the docker containers Up 
3. Add the packages in airflow , worker and scheduler for snowflake and AWS

##check the containers name
sudo docker-compose ps
####Modify the docker containers with the required libraries (Make sure you place the correct containers name from above command)
sudo docker exec -ti -u root airflow_airflow_1 bash
pip install sagemaker
.  /opt/bitnami/airflow/venv/bin/activate
pip install awscli
pip install snowflake
pip install snowflake-sqlalchemy
pip install snowflake-connector-python
pip install sagemaker
exit

sudo docker exec -ti -u root airflow_airflow-worker_1 bash
pip install sagemaker
pip install snowflake
pip install snowflake-sqlalchemy
pip install snowflake-connector-python
.  /opt/bitnami/airflow/venv/bin/activate
pip install awscli
pip install sagemaker
pip install snowflake
pip install snowflake-sqlalchemy
pip install snowflake-connector-python
exit

sudo docker exec -ti -u root airflow_airflow-scheduler_1 bash
pip install sagemaker
.  /opt/bitnami/airflow/venv/bin/activate
pip install awscli
pip install sagemaker
pip install snowflake
pip install snowflake-sqlalchemy
pip install snowflake-connector-python
exit

sudo docker exec -ti -u root airflow_airflow_1 bash
pip install awscli
aws configure

/opt/bitnami/python/bin/pip install snowflake-sqlalchemy
/opt/bitnami/python/bin/pip install sagemaker
/opt/bitnami/python/bin/pip install snowflake-connector-python
exit

sudo docker exec -ti  -u root airflow_airflow-scheduler_1 bash
pip install awscli
aws configure

/opt/bitnami/python/bin/pip install snowflake-sqlalchemy
/opt/bitnami/python/bin/pip install sagemaker
/opt/bitnami/python/bin/pip install snowflake-connector-python
exit 

sudo docker exec -ti -u root  airflow_airflow-worker_1 bash
pip install awscli
aws configure

/opt/bitnami/python/bin/pip install snowflake-sqlalchemy
/opt/bitnami/python/bin/pip install sagemaker
/opt/bitnami/python/bin/pip install snowflake-connector-python

exit

4. Restarted the containers for airflow , scheduler and worker  sudo docker-compose restart airflow airflow-scheduler airflow-worker

**Describe the results you received:**

Even after this I cannot see the snowflake connector in Airflow UI in the connections and while importing DAG's I see below error 

  File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/airflow/contrib/hooks/snowflake_hook.py", line 24, in <module>
    from airflow.providers.snowflake.hooks.snowflake import SnowflakeHook  # noqa
ModuleNotFoundError: No module named 'airflow.providers.snowflake'

**Describe the results you expected:**

I expected to see the snowflake connector in the airflow UI in the connections page

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

- Output of `docker version`:

```
Client:
 Version:           20.10.4
 API version:       1.41
 Go version:        go1.15.8
 Git commit:        d3cb89e
 Built:             Mon Mar 29 18:54:36 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

```

- Output of `docker info`:

```
Client:
 Context:    default
 Debug Mode: false

Server:
 Containers: 10
  Running: 5
  Paused: 0
  Stopped: 5
 Images: 15
 Server Version: 20.10.4
 Storage Driver: overlay2
  Backing Filesystem: xfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 05f951a3781f4f2c1911b05e61c160e9c30eaa8e
 runc version: 12644e614e25b05da6fd08a38ffa0cfe1903fdec
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.14.231-173.361.amzn2.x86_64
 Operating System: Amazon Linux 2
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 3.794GiB
 Name: ip-172-31-7-57.ap-southeast-1.compute.internal
 ID: U6ZC:2MNU:A2EQ:3I5T:A7QV:OQD5:KAQV:C2IX:GAN7:HGIX:I47T:ZD6O
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.26.2, build unknown
docker-py version: 4.4.4
CPython version: 2.7.18
OpenSSL version: OpenSSL 1.0.2k-fips  26 Jan 2017

```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

**Comment by javsalgar** [comment]
Hi,

I recall some users having issues with Python Imports and it was because the PYTHONPATH variable was not set correctly. Could you check what the PYTHONPATH variable value is and, by changing it in the docker-compose.yaml file, the imports works as expected?

**Comment by sobee07** [comment]
Hi javsalgar,

Can help provide the exact steps to use  so that I can try and implement the same

**Comment by sobee07** [comment]
I cannot sent the tarball of my containers as the size is huge around 1.9Gb , The problem i am facing is even after adding the python dependencies for snowflake connector , in the airflow UI I dont see the connection appearing at all. Is there anything missing in my installation listed above ?

![image](https://user-images.githubusercontent.com/29519769/121332981-f16ac000-c94a-11eb-80d8-18e9bea7fd15.png)

**Comment by javsalgar** [comment]
Hi,

And are you able to send the dags that you are using, together with the scripts? That should have a smaller size. I don't have experience with the snowflake connector, that's why I'd like to reproduce it in my side.
